version: "3.9"
services:
  pingopongo: 
    restart: unless-stopped
    build: .
    container_name: pingopongo 
    ports: 
      - "${PINGOPONGO_PORT}:8000"
    volumes: 
      - ".:/code"
      - "${PINGOPONGO_DATA}:/code/data"
      - "${PINGOPONGO_CONFIG}:/code/conf"
