name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout 
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      run: docker buildx create --use && docker run --privileged --rm tonistiigi/binfmt --install all
    -
      name: Build and push
      run:  docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag ${{secrets.DOCKER_USERNAME}}/pingopongo-be --push .
